"""Initial schema with points ledger and stage events

Revision ID: 238fc9ab4aa0
Revises: 
Create Date: 2025-08-25 12:54:17.123176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238fc9ab4aa0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_stage_events_deal_id'), 'deal_stage_events', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_stage_events_id'), 'deal_stage_events', ['id'], unique=False)
    op.create_table('points_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('STAGE_ADVANCE', 'BONUS_LEAD_INTAKE_SAME_DAY', 'BONUS_WON_FAST', 'DEAL_ROTTED_SUSPENSION', 'DEAL_REVIVED', name='pointeventtype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_ledger_deal_id'), 'points_ledger', ['deal_id'], unique=False)
    op.create_index(op.f('ix_points_ledger_id'), 'points_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_points_ledger_user_id'), 'points_ledger', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_ledger_user_id'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_id'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_deal_id'), table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_index(op.f('ix_deal_stage_events_id'), table_name='deal_stage_events')
    op.drop_index(op.f('ix_deal_stage_events_deal_id'), table_name='deal_stage_events')
    op.drop_table('deal_stage_events')
    # ### end Alembic commands ###
